dir: '{{.InterfaceDir}}'
pkgname: '{{.SrcPackageName}}_test'
filename: '{{ .InterfaceName | snakecase }}_mock_test.go'
structname: '{{.InterfaceName}}'
template: testify
packages:
    github.com/sergisimo/ledger/internal/platform/usecase:
      config:
          dir: '{{.InterfaceDir}}/{{.SrcPackageName}}test'
          structname: '{{.InterfaceName}}'
          pkgname: '{{.SrcPackageName}}test'
          filename: '{{ .InterfaceName | snakecase }}_mock.go'
      interfaces:
          Creator: {}
          Deleter: {}
          Getter: {}
          Lister: {}
          Patcher: {}
