FROM golang:1.26 AS build_ledger
ENV CGO_ENABLED=0
ARG BUILD_TAG

RUN mkdir /service
COPY . /service
WORKDIR /service
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

WORKDIR /service/cmd/ledger
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go build -ldflags "-X main.tag=${BUILD_TAG}" -o ledger

FROM alpine:3.24
ARG BUILD_DATE
ARG BUILD_TAG
COPY --from=build_ledger /service/cmd/ledger/ledger /service/ledger
WORKDIR /service
CMD ["./ledger"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="ledger" \
      org.opencontainers.image.authors="Sergi Simó Bosquet <sergisimo10@gmail.com>" \
      org.opencontainers.image.source="https://github.com/sergisimo/ledger" \
      org.opencontainers.image.revision="${BUILD_TAG}" \
      org.opencontainers.image.vendor="Sergi Simó Bosquet"
