// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasetest

import (
	"context"

	"github.com/sergisimo/ledger/internal/platform/query"
	mock "github.com/stretchr/testify/mock"
)

// NewDeleter creates a new instance of Deleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Deleter {
	mock := &Deleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Deleter is an autogenerated mock type for the Deleter type
type Deleter struct {
	mock.Mock
}

type Deleter_Expecter struct {
	mock *mock.Mock
}

func (_m *Deleter) EXPECT() *Deleter_Expecter {
	return &Deleter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type Deleter
func (_mock *Deleter) Delete(context1 context.Context, deleteType query.DeleteType, srchOptions ...query.SrchOption) error {
	var tmpRet mock.Arguments
	if len(srchOptions) > 0 {
		tmpRet = _mock.Called(context1, deleteType, srchOptions)
	} else {
		tmpRet = _mock.Called(context1, deleteType)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, query.DeleteType, ...query.SrchOption) error); ok {
		r0 = returnFunc(context1, deleteType, srchOptions...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Deleter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Deleter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteType query.DeleteType
//   - srchOptions ...query.SrchOption
func (_e *Deleter_Expecter) Delete(context1 any, deleteType any, srchOptions ...any) *Deleter_Delete_Call {
	return &Deleter_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{context1, deleteType}, srchOptions...)...)}
}

func (_c *Deleter_Delete_Call) Run(run func(context1 context.Context, deleteType query.DeleteType, srchOptions ...query.SrchOption)) *Deleter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 query.DeleteType
		if args[1] != nil {
			arg1 = args[1].(query.DeleteType)
		}
		var arg2 []query.SrchOption
		var variadicArgs []query.SrchOption
		if len(args) > 2 {
			variadicArgs = args[2].([]query.SrchOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Deleter_Delete_Call) Return(err error) *Deleter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Deleter_Delete_Call) RunAndReturn(run func(context1 context.Context, deleteType query.DeleteType, srchOptions ...query.SrchOption) error) *Deleter_Delete_Call {
	_c.Call.Return(run)
	return _c
}
