// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasetest

import (
	"context"

	"github.com/sergisimo/ledger/internal/platform/query"
	"github.com/sergisimo/ledger/internal/platform/resource"
	mock "github.com/stretchr/testify/mock"
)

// NewLister creates a new instance of Lister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLister[R resource.Resource](t interface {
	mock.TestingT
	Cleanup(func())
}) *Lister[R] {
	mock := &Lister[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Lister is an autogenerated mock type for the Lister type
type Lister[R resource.Resource] struct {
	mock.Mock
}

type Lister_Expecter[R resource.Resource] struct {
	mock *mock.Mock
}

func (_m *Lister[R]) EXPECT() *Lister_Expecter[R] {
	return &Lister_Expecter[R]{mock: &_m.Mock}
}

// List provides a mock function for the type Lister
func (_mock *Lister[R]) List(context1 context.Context, srchOptions ...query.SrchOption) (resource.List[R], error) {
	// query.SrchOption
	_va := make([]any, len(srchOptions))
	for _i := range srchOptions {
		_va[_i] = srchOptions[_i]
	}
	var _ca []any
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.List[R]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...query.SrchOption) (resource.List[R], error)); ok {
		return returnFunc(context1, srchOptions...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...query.SrchOption) resource.List[R]); ok {
		r0 = returnFunc(context1, srchOptions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.List[R])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...query.SrchOption) error); ok {
		r1 = returnFunc(context1, srchOptions...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Lister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Lister_List_Call[R resource.Resource] struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - srchOptions ...query.SrchOption
func (_e *Lister_Expecter[R]) List(context1 any, srchOptions ...any) *Lister_List_Call[R] {
	return &Lister_List_Call[R]{Call: _e.mock.On("List",
		append([]any{context1}, srchOptions...)...)}
}

func (_c *Lister_List_Call[R]) Run(run func(context1 context.Context, srchOptions ...query.SrchOption)) *Lister_List_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []query.SrchOption
		variadicArgs := make([]query.SrchOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(query.SrchOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Lister_List_Call[R]) Return(list resource.List[R], err error) *Lister_List_Call[R] {
	_c.Call.Return(list, err)
	return _c
}

func (_c *Lister_List_Call[R]) RunAndReturn(run func(context1 context.Context, srchOptions ...query.SrchOption) (resource.List[R], error)) *Lister_List_Call[R] {
	_c.Call.Return(run)
	return _c
}
