// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasetest

import (
	"context"

	"github.com/sergisimo/ledger/internal/platform/query"
	mock "github.com/stretchr/testify/mock"
)

// NewPatcher creates a new instance of Patcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPatcher[R any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Patcher[R] {
	mock := &Patcher[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Patcher is an autogenerated mock type for the Patcher type
type Patcher[R any] struct {
	mock.Mock
}

type Patcher_Expecter[R any] struct {
	mock *mock.Mock
}

func (_m *Patcher[R]) EXPECT() *Patcher_Expecter[R] {
	return &Patcher_Expecter[R]{mock: &_m.Mock}
}

// Patch provides a mock function for the type Patcher
func (_mock *Patcher[R]) Patch(context1 context.Context, patchOptions ...query.PatchOption) (R, error) {
	// query.PatchOption
	_va := make([]any, len(patchOptions))
	for _i := range patchOptions {
		_va[_i] = patchOptions[_i]
	}
	var _ca []any
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 R
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...query.PatchOption) (R, error)); ok {
		return returnFunc(context1, patchOptions...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...query.PatchOption) R); ok {
		r0 = returnFunc(context1, patchOptions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(R)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...query.PatchOption) error); ok {
		r1 = returnFunc(context1, patchOptions...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Patcher_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type Patcher_Patch_Call[R any] struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - context1 context.Context
//   - patchOptions ...query.PatchOption
func (_e *Patcher_Expecter[R]) Patch(context1 any, patchOptions ...any) *Patcher_Patch_Call[R] {
	return &Patcher_Patch_Call[R]{Call: _e.mock.On("Patch",
		append([]any{context1}, patchOptions...)...)}
}

func (_c *Patcher_Patch_Call[R]) Run(run func(context1 context.Context, patchOptions ...query.PatchOption)) *Patcher_Patch_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []query.PatchOption
		variadicArgs := make([]query.PatchOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(query.PatchOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Patcher_Patch_Call[R]) Return(v R, err error) *Patcher_Patch_Call[R] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Patcher_Patch_Call[R]) RunAndReturn(run func(context1 context.Context, patchOptions ...query.PatchOption) (R, error)) *Patcher_Patch_Call[R] {
	_c.Call.Return(run)
	return _c
}
