apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger
  namespace: ledger
  labels:
    app: ledger
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ledger
  template:
    metadata:
      labels:
        app: ledger
    spec:
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ .Values.container.resources.requests.cpu | quote }}
              memory: {{ .Values.container.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.container.resources.limits.cpu | quote }}
              memory: {{ .Values.container.resources.limits.memory | quote }}
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          ports:
            {{- range .Values.container.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
