apiVersion: v1
kind: Service
metadata:
  name: ledger
  namespace: ledger
  labels:
    app: ledger
spec:
  type: ClusterIP
  selector:
    app: ledger
  ports:
    {{- range .Values.container.ports }}
    - name: {{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
